name: subgraphx
channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - python=3.7
  - pytorch=1.10
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - pip:
    - -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - torch-spline-conv
    - torch-geometric
    - dive-into-graphs==0.1.2

