name: subgraphx
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pip
  - swig
  - git
  - pytorch==1.10
  - pip:
    - numpy
    - matplotlib
    - scipy
    - torch_scatter
    - torch_sparse
    - torch_cluster
    - torch_spline-conv
    - torch_geometric
    - dive-into-graphs

